"""
Streamlit Explorer — Mice Protein Expression / Down Syndrome Drug-Response Analysis

Run locally with:
    streamlit run streamlit_app.py

Requires Data_Cortex_Nuclear.xls (and, optionally, treatment_response_analysis.csv
generated by the EDA notebook) in the same folder as this script.
"""

import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import streamlit as st
from sklearn.decomposition import PCA
from sklearn.impute import KNNImputer


def fig_to_png_bytes(fig):
    """Convert a matplotlib figure to PNG bytes for st.download_button."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=200, bbox_inches="tight")
    buf.seek(0)
    return buf.getvalue()


def df_to_csv_bytes(dataframe):
    return dataframe.to_csv(index=True).encode("utf-8")


# Biological context for all 77 proteins, grounded in the dataset's source paper:
# Higuera C, Gardiner KJ, Cios KJ (2015) "Self-Organizing Feature Maps Identify
# Proteins Critical to Learning in a Mouse Model of Down Syndrome." PLoS ONE 10(6): e0129126.
#
# Notes starting with "In this study:" describe something the paper explicitly
# found for that protein (written in plain language, not statistics jargon).
# Notes without that prefix are general, well-established biological function --
# not a dataset-specific claim from the paper, just standard context for what
# the protein normally does. Plain-language glossary used throughout:
#   "learned successfully" = control mice that learned the task normally
#   "failed to learn" = trisomic mice that did not learn (no drug help)
#   "learning was rescued by the drug" = trisomic mice that DID learn, after Memantine
BIOLOGY_PROFILES = {
    "ADARB1_N": {"role": "An enzyme that edits RNA, located near the Down syndrome-critical region of chromosome 21.", "problem": "Because this gene sits on chromosome 21, trisomic mice carry one extra working copy of it -- and having too much of it, rather than too little, is thought to disrupt normal brain function.", "discovery": None},
    "AKT_N": {"role": "Part of the same cell-growth signal chain as MTOR.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": "its level specifically stood out in trisomic mice whose learning was rescued by the drug."},
    "AMPKA_N": {"role": "Senses how much energy a cell has available and can adjust the mTOR growth signal chain accordingly.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": "its level was different between control and trisomic mice."},
    "APP_N": {"role": "A protein connected to the same chemical-signal system the NMDA receptor uses.", "problem": "Because this gene sits on chromosome 21, trisomic mice carry one extra working copy of it -- and having too much of it, rather than too little, is thought to disrupt normal brain function.", "discovery": "its level clearly separated trisomic mice that failed to learn from mice that learned successfully."},
    "ARC_N": {"role": "A gene that switches on within minutes when a neuron fires, directly involved in strengthening synapses during learning.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level changed specifically when trisomic mice were given the drug."},
    "AcetylH3K9_N": {"role": "A chemical tag added to the proteins DNA is wrapped around, which switches nearby genes on.", "problem": "In Down syndrome models, the way genes get switched on or off during learning can be disrupted, and marks like this one are part of that switching system.", "discovery": "untreated trisomic mice stood out uniquely on this protein compared to every other group."},
    "BAD_N": {"role": "Pushes a cell toward self-destructing; works alongside BAX_N and BCL2_N in the same cell-survival balance.", "problem": "An imbalance in this cell-survival system has been linked to how neurons cope with the extra genetic material trisomic mice carry.", "discovery": None},
    "BAX_N": {"role": "Pushes a damaged cell toward self-destructing when activated.", "problem": "An imbalance in this cell-survival system has been linked to how neurons cope with the extra genetic material trisomic mice carry.", "discovery": "its level was different in trisomic mice that failed to learn."},
    "BCL2_N": {"role": "Blocks BAX_N's self-destruct signal, helping cells survive; has also been linked to learning-related changes in past studies of this model.", "problem": "An imbalance in this cell-survival system has been linked to how neurons cope with the extra genetic material trisomic mice carry.", "discovery": None},
    "BDNF_N": {"role": "A growth factor that helps neurons strengthen their connections during learning.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level was different in trisomic mice that failed to learn, compared to mice that learned successfully."},
    "BRAF_N": {"role": "One link in a chain of proteins that pass a chemical signal from outside a neuron to its DNA, switching genes on in response to activity -- this chain is tied to learning.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": "its level changed both in mice that learned successfully and in mice whose learning was rescued by the drug."},
    "Bcatenin_N": {"role": "Part of a signal chain (called Wnt) that also shapes the physical structure of synapses.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": None},
    "CAMKII_N": {"role": "A protein that strengthens the connection between two neurons when they fire together; works closely with the NMDA receptor.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": None},
    "CDK5_N": {"role": "Involved in neuron signaling and in maintaining a neuron's internal shape.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level stood out in mice that learned successfully, and separately was different between drug-rescued and untreated trisomic mice."},
    "CREB_N": {"role": "A protein that helps turn a neuron's short-term activity into a long-lasting memory.", "problem": "In Down syndrome models, this memory-forming switch often fails to activate properly after a new experience, making it harder to convert that experience into a lasting memory.", "discovery": None},
    "CaNA_N": {"role": "A protein that reacts to calcium entering a neuron and passes that signal onward.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level was different in trisomic mice that failed to learn, and separately, untreated trisomic mice stood out uniquely on this protein compared to every other group."},
    "DSCR1_N": {"role": "Also called RCAN1; sits directly inside the Down Syndrome Critical Region on chromosome 21, and blocks a calcium-signal chain relevant to trisomy effects.", "problem": "Because this gene sits on chromosome 21, trisomic mice carry one extra working copy of it -- and having too much of it, rather than too little, is thought to disrupt normal brain function.", "discovery": None},
    "DYRK1A_N": {"role": "A gene located on human chromosome 21 (the Down syndrome region).", "problem": "Because this gene sits on chromosome 21, trisomic mice carry one extra working copy of it -- and having too much of it, rather than too little, is thought to disrupt normal brain function.", "discovery": "its level was higher in trisomic mice, and clearly changed both in mice that learned successfully and in mice whose learning was rescued by the drug."},
    "EGR1_N": {"role": "A gene that switches on within minutes when a neuron fires; involved in forming memories.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level was different in trisomic mice that failed to learn, compared to mice that learned successfully."},
    "ELK_N": {"role": "Switches on genes after a neuron receives a signal through the ERK chain.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "ERBB4_N": {"role": "Involved in how synapses develop and function.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level changed specifically when trisomic mice were given the drug."},
    "ERK_N": {"role": "Another link in that same signal chain, well known to be important for forming memories.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "GFAP_N": {"role": "A marker of activity in support cells (astrocytes) that surround and assist neurons.", "problem": "Brain-support-cell activity and inflammation are often elevated in Down syndrome models, which can interfere with the environment neurons need in order to learn effectively.", "discovery": "its level was different between drug-rescued and untreated trisomic mice."},
    "GSK3B_N": {"role": "A protein that can turn other proteins on or off by adding a chemical tag to them; it sits inside several signal chains that shape how synapses change with learning.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": None},
    "GluR3_N": {"role": "A building-block piece of a different receptor (AMPA) that works alongside the NMDA receptor.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": "its level was different in trisomic mice that failed to learn, compared to mice that learned successfully."},
    "GluR4_N": {"role": "A building-block piece of the AMPA receptor.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": "its level was different in trisomic mice that failed to learn."},
    "H3AcK18_N": {"role": "Another DNA-wrapping tag that switches genes on, linked to the gene-expression changes that happen during learning.", "problem": "In Down syndrome models, the way genes get switched on or off during learning can be disrupted, and marks like this one are part of that switching system.", "discovery": None},
    "H3MeK4_N": {"role": "Another DNA-wrapping tag associated with genes being actively read and used.", "problem": "In Down syndrome models, the way genes get switched on or off during learning can be disrupted, and marks like this one are part of that switching system.", "discovery": None},
    "IL1B_N": {"role": "A molecule the immune system releases to signal inflammation; brain inflammation has been linked to learning problems.", "problem": "Brain-support-cell activity and inflammation are often elevated in Down syndrome models, which can interfere with the environment neurons need in order to learn effectively.", "discovery": "its level was different between control and trisomic mice."},
    "ITSN1_N": {"role": "A chromosome-21-linked gene involved in how neurons recycle their internal machinery.", "problem": "Because this gene sits on chromosome 21, trisomic mice carry one extra working copy of it -- and having too much of it, rather than too little, is thought to disrupt normal brain function.", "discovery": "its level changed in mice that learned successfully, and separately in trisomic mice that failed to learn."},
    "JNK_N": {"role": "A protein that responds to cell stress, part of a signal chain separate from the main learning-linked one.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "MEK_N": {"role": "Sits upstream of ERK in the same signal chain linked to learning.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "MTOR_N": {"role": "The central protein in the cell-growth signal chain tied to how synapses change during learning.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": "its level specifically stood out in trisomic mice whose learning was rescued by the drug."},
    "NR1_N": {"role": "One of three building-block pieces that join together to form the NMDA receptor -- the exact target Memantine acts on.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": None},
    "NR2A_N": {"role": "One of three building-block pieces that join together to form the NMDA receptor, Memantine's direct target.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": None},
    "NR2B_N": {"role": "One of three building-block pieces that join together to form the NMDA receptor.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": "its level was different in trisomic mice that failed to learn."},
    "NUMB_N": {"role": "Helps control how NMDA receptors (Memantine's target) are moved around and managed inside the neuron.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": None},
    "P3525_N": {"role": "Included in the original study's protein panel for its relevance to brain development and function.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level changed specifically when trisomic mice were given the drug, and separately, untreated trisomic mice stood out uniquely on this protein."},
    "P38_N": {"role": "Passes along a chemical signal that starts at the NMDA receptor (Memantine's target).", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": "its level showed up across several comparisons, including failed learning, drug response, and control-vs-trisomic differences."},
    "P70S6_N": {"role": "Downstream of the mTOR growth signal chain; relevant to how neurons build new proteins.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": None},
    "PKCA_N": {"role": "Part of a family of proteins that turn other proteins on by tagging them, linked to how synapses change with learning.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level was different between control and trisomic mice."},
    "PSD95_N": {"role": "A protein that holds receptors in place at the synapse, like scaffolding for the connection point between two neurons.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": None},
    "RAPTOR_N": {"role": "A core building-block piece of the mTOR growth-signaling machine.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": "its level was different between control and trisomic mice."},
    "RRP1_N": {"role": "Involved in building ribosomes, the cell's protein-making machinery.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level was different between drug-rescued and untreated trisomic mice."},
    "RSK_N": {"role": "Works downstream of the same signal chain as ERK, linked to learning.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "S6_N": {"role": "Part of a separate chain of proteins (called mTOR) that tells a cell to grow and build new proteins.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": "its level specifically stood out in control mice that learned successfully."},
    "SHH_N": {"role": "A protein important during brain development, also linked to brain-structure differences seen in Down syndrome models.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": None},
    "SNCA_N": {"role": "A protein normally found at the synapse, heavily studied in neurodegeneration research.", "problem": "Brain-support-cell activity and inflammation are often elevated in Down syndrome models, which can interfere with the environment neurons need in order to learn effectively.", "discovery": "its level changed specifically when trisomic mice were given the drug."},
    "SOD1_N": {"role": "An enzyme that mops up cell-damaging byproducts; higher cell damage of this kind is a known feature of Down syndrome models.", "problem": "Because this gene sits on chromosome 21, trisomic mice carry one extra working copy of it -- and having too much of it, rather than too little, is thought to disrupt normal brain function.", "discovery": "its level changed in mice that learned successfully, and separately in trisomic mice that failed to learn."},
    "SYP_N": {"role": "Found in the small packets neurons use to release signaling chemicals; commonly used as a marker of how many synapses are present.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": None},
    "TIAM1_N": {"role": "Helps shape the small bumps (dendritic spines) on a neuron where synapses form.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": None},
    "TRKA_N": {"role": "A receptor that helps neurons survive and respond to growth signals.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": None},
    "Tau_N": {"role": "A structural protein that helps hold a neuron's internal skeleton together, heavily studied in Alzheimer's research.", "problem": "Brain-support-cell activity and inflammation are often elevated in Down syndrome models, which can interfere with the environment neurons need in order to learn effectively.", "discovery": "its level was different between control and trisomic mice."},
    "Ubiquitin_N": {"role": "A small tag that gets attached to proteins to mark them for recycling/breakdown inside the cell.", "problem": "In Down syndrome models, the way genes get switched on or off during learning can be disrupted, and marks like this one are part of that switching system.", "discovery": "its level showed up across several learning-related comparisons."},
    "nNOS_N": {"role": "Helps neurons send a chemical signal (nitric oxide) to nearby cells.", "problem": "Brain-support-cell activity and inflammation are often elevated in Down syndrome models, which can interfere with the environment neurons need in order to learn effectively.", "discovery": "its level was different between control and trisomic mice."},
    "pAKT_N": {"role": "The switched-on version of AKT, reflecting the same growth-signal activity as AKT_N.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": None},
    "pBRAF_N": {"role": "The switched-on version of BRAF (a small chemical tag gets added to turn it on), part of the same learning-linked signal chain.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "pCAMKII_N": {"role": "The switched-on version of CAMKII.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": "its level was different in trisomic mice that failed to learn, compared to mice that learned successfully."},
    "pCASP9_N": {"role": "The switched-on version of a protein that helps trigger a cell's self-destruct process.", "problem": "An imbalance in this cell-survival system has been linked to how neurons cope with the extra genetic material trisomic mice carry.", "discovery": None},
    "pCFOS_N": {"role": "Switches on within minutes of a neuron firing; commonly used as a marker of which neurons were recently active.", "problem": "In Down syndrome models, this quick-response marker often doesn't switch on as expected after a new experience, suggesting the neurons involved aren't responding normally to new learning situations.", "discovery": None},
    "pCREB_N": {"role": "The switched-on version of a protein that helps turn a neuron's short-term activity into a long-lasting memory.", "problem": "In Down syndrome models, this memory-forming switch often fails to activate properly after a new experience, making it harder to convert that experience into a lasting memory.", "discovery": None},
    "pELK_N": {"role": "The switched-on version of ELK, directly linked to gene activity triggered by learning-related signaling.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "pERK_N": {"role": "The switched-on version of ERK.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": "its level changed in mice that learned successfully, and separately in trisomic mice that failed to learn -- matching what's already known about this protein's role in learning."},
    "pGSK3B_N": {"role": "One switched-on version of GSK3B (it has more than one on/off switch).", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": "its level specifically stood out in control mice that learned successfully."},
    "pGSK3B_Tyr216_N": {"role": "A different switched-on version of GSK3B (a separate on/off switch on the same protein), reflecting a less-studied side of its regulation.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": None},
    "pJNK_N": {"role": "The switched-on version of a stress-response protein, part of a separate chain from the main learning-linked one.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "pMEK_N": {"role": "Works just upstream of BRAF and ERK in the same learning-linked signal chain.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": None},
    "pMTOR_N": {"role": "The switched-on version of MTOR.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": "its level changed specifically when trisomic mice were given the drug."},
    "pNR1_N": {"role": "The switched-on version of NR1.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": "its level changed when Memantine was given to control mice, matching the drug's known target."},
    "pNR2A_N": {"role": "The switched-on version of NR2A.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": "its level changed specifically when trisomic mice were given the drug, and separately untreated trisomic mice stood out uniquely on this protein."},
    "pNR2B_N": {"role": "The switched-on version of NR2B. NR2B, NR2A_N, and NR1_N are the three pieces that snap together to build the NMDA receptor, the exact target Memantine acts on.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": None},
    "pNUMB_N": {"role": "The switched-on version of NUMB.", "problem": "In Down syndrome models, this receptor system tends to run overactive, which can interfere with learning rather than support it -- part of why Memantine, a drug that calms this exact system, has been tested as a treatment.", "discovery": "its level specifically stood out in control mice that learned successfully."},
    "pP70S6_N": {"role": "The switched-on version of P70S6.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": "its level was different in trisomic mice that failed to learn, and separately changed when trisomic mice were given the drug."},
    "pPKCAB_N": {"role": "The switched-on version of a related member of that same protein family.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level changed specifically when trisomic mice were given the drug."},
    "pPKCG_N": {"role": "The switched-on version of a protein in that same family.", "problem": "Down syndrome models often show altered synapse structure and formation, which can make it harder to build the new connections that learning requires.", "discovery": "its level changed specifically when trisomic mice were given the drug, and separately, untreated trisomic mice stood out uniquely on this protein -- this is also the single strongest drug-response signal found in this app's own analysis."},
    "pRSK_N": {"role": "The switched-on version of RSK.", "problem": "In Down syndrome models, this signaling chain often doesn't switch on properly after a new experience, making it harder for the brain to convert that experience into a lasting memory.", "discovery": "untreated trisomic mice stood out uniquely on this protein compared to every other group."},
    "pS6_N": {"role": "The switched-on version of S6, reflecting the same cell-growth activity as S6_N.", "problem": "In Down syndrome models, this growth-signaling system is often out of balance, which can disrupt how neurons build the new connections needed for learning.", "discovery": None},
}


# ---------------------------------------------------------------
# Biological pathway / family groupings, for the "sanity check" view below.
# Grouped by known biological role (physical receptor complexes, enzyme
# families, signaling cascades, etc.) -- this grouping itself is standard
# biology, not something discovered by this project's analysis. What IS
# this project's own analysis is the correlation check run on each group
# (see compute_family_correlations / render_pathway_groups below), which
# tests whether members of each group actually move together in this
# specific dataset, rather than just assuming they do because they share
# a textbook label.
# ---------------------------------------------------------------
PROTEIN_FAMILIES = {
    "NMDA receptor complex": ["NR1_N", "NR2A_N", "NR2B_N", "pNR1_N", "pNR2A_N", "pNR2B_N"],
    "ERK/MAPK learning-signal chain": ["BRAF_N", "pBRAF_N", "MEK_N", "pMEK_N", "ERK_N", "pERK_N",
                                       "ELK_N", "pELK_N", "RSK_N", "pRSK_N"],
    "CREB / immediate-early genes": ["CREB_N", "pCREB_N", "ARC_N", "EGR1_N", "pCFOS_N"],
    "mTOR growth-signaling chain": ["MTOR_N", "pMTOR_N", "RAPTOR_N", "AKT_N", "pAKT_N",
                                     "AMPKA_N", "P70S6_N", "pP70S6_N", "S6_N", "pS6_N"],
    "Apoptosis / cell survival": ["BAX_N", "BAD_N", "BCL2_N", "pCASP9_N"],
    "PKC family": ["PKCA_N", "pPKCAB_N", "pPKCG_N"],
    "AMPA receptor": ["GluR3_N", "GluR4_N"],
    "GSK3B variants": ["GSK3B_N", "pGSK3B_N", "pGSK3B_Tyr216_N"],
    "Chr21 / Down-syndrome-critical genes": ["DYRK1A_N", "ITSN1_N", "DSCR1_N", "ADARB1_N"],
}


def render_biology_profile(protein_name):
    """Renders a 3-part protein profile: Normal Role -> Down Syndrome Problem ->
    Experiment's Discovery. The Discovery section only appears if the original
    study reported an actual finding for this protein; otherwise it's honestly
    omitted rather than filled with a guess."""
    profile = BIOLOGY_PROFILES.get(protein_name)
    if profile is None:
        st.caption("No curated biological note available yet for this protein.")
        return

    st.markdown(f"##### \U0001F9E0 Its Normal Role (Supporting Memory)")
    st.markdown(profile["role"])

    st.markdown(f"##### \u26A0\uFE0F The Down Syndrome Problem")
    st.markdown(profile["problem"])

    st.markdown(f"##### \U0001F52C The Experiment's Discovery")
    if profile["discovery"]:
        st.success("\u2713 A specific finding reported by the original study for this exact protein:")
        st.info(profile["discovery"])
    else:
        st.caption(
            "\u2139\ufe0f The original study did not report a specific finding for this "
            "protein -- the sections above are general background only."
        )


sns.set_style("whitegrid")

st.set_page_config(page_title="Mice Protein Explorer", layout="wide")

st.markdown("""
<style>
.stApp {
    background: linear-gradient(135deg, #0b1d3a 0%, #16213e 50%, #1a1a2e 100%);
}
h1, h2, h3 {
    background: linear-gradient(90deg, #1D9E75, #378ADD, #D4537E);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    font-weight: 700 !important;
}
[data-testid="stMetric"] {
    background: linear-gradient(135deg, rgba(29,158,117,0.18), rgba(55,138,221,0.18));
    border: 1px solid rgba(93,202,165,0.35);
    border-radius: 14px;
    padding: 14px 10px;
}
[data-testid="stMetricLabel"] {
    color: #9FE1CB !important;
}
[data-testid="stMetricValue"] {
    color: #E6F1FB !important;
}
.stButton>button, .stDownloadButton>button {
    background: linear-gradient(90deg, #1D9E75, #378ADD);
    color: white;
    border: none;
    border-radius: 10px;
    font-weight: 600;
    transition: transform 0.1s ease;
}
.stButton>button:hover, .stDownloadButton>button:hover {
    transform: scale(1.03);
    background: linear-gradient(90deg, #0F6E56, #185FA5);
    color: white;
}
[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #16213e 0%, #0b1d3a 100%);
    border-right: 1px solid rgba(93,202,165,0.25);
}
.stAlert {
    border-radius: 12px;
}
[data-testid="stExpander"] {
    border: 1px solid rgba(212,83,126,0.3);
    border-radius: 12px;
}
div[role="radiogroup"] label {
    background: rgba(29,158,117,0.08);
    border-radius: 8px;
    padding: 4px 10px;
    margin-bottom: 2px;
}
hr {
    border-color: rgba(93,202,165,0.25) !important;
}
</style>
""", unsafe_allow_html=True)


# ---------------------------------------------------------------
# Data loading (cached so KNN imputation only runs once per session)
# ---------------------------------------------------------------
@st.cache_data
def load_data():
    df = pd.read_excel("Data_Cortex_Nuclear.xls")
    protein_cols = [c for c in df.columns if c not in
                    ["MouseID", "Genotype", "Treatment", "Behavior", "class"]]

    imputer = KNNImputer(n_neighbors=5)
    X = pd.DataFrame(imputer.fit_transform(df[protein_cols]), columns=protein_cols)
    X[["Genotype", "Treatment", "Behavior", "class"]] = df[
        ["Genotype", "Treatment", "Behavior", "class"]
    ].values
    return X, protein_cols


@st.cache_data
def load_candidates():
    try:
        return pd.read_csv("treatment_response_analysis.csv")
    except FileNotFoundError:
        return None


df, protein_cols = load_data()
candidates = load_candidates()

# ---------------------------------------------------------------
# Sidebar controls
# ---------------------------------------------------------------
st.sidebar.title("Protein Explorer")
st.sidebar.markdown(
    "Down Syndrome Drug-Response Biomarker Analysis \u2014 "
    "Mice Protein Expression Dataset"
)

# Build a "candidate biomarkers" quick-select list from the EDA results,
# so a user doesn't have to already know a protein's code name to find
# something meaningful.
candidate_names = []
if candidates is not None and "significant" in candidates.columns:
    candidate_names = candidates[
        candidates["shifted_toward_control"] & candidates["significant"]
    ].sort_values("improvement", ascending=False)["protein"].tolist()

st.sidebar.markdown("### Which protein?")
pick_mode = st.sidebar.radio(
    "How do you want to choose?",
    ["Candidate biomarkers (recommended)", "Search all 77 proteins"],
    help=(
        "Candidate biomarkers are proteins that BOTH shifted toward healthy "
        "control levels after treatment AND passed a statistical significance "
        "test — these are the most meaningful ones to look at first."
    )
)

if pick_mode == "Candidate biomarkers (recommended)" and candidate_names:
    selected_protein = st.sidebar.selectbox(
        "Select a candidate biomarker",
        candidate_names,
        help="Ranked from strongest to weakest treatment response."
    )
    st.sidebar.caption(
        f"\u2705 This protein passed both EDA filters: shifted toward control "
        f"levels AND statistically significant (p < 0.05)."
    )
else:
    selected_protein = st.sidebar.selectbox(
        "Select any protein",
        sorted(protein_cols),
        index=sorted(protein_cols).index("pPKCG_N") if "pPKCG_N" in protein_cols else 0
    )
    if candidates is not None and "significant" in candidates.columns:
        row = candidates[candidates["protein"] == selected_protein]
        if len(row) and not (row.iloc[0]["shifted_toward_control"] and row.iloc[0]["significant"]):
            st.sidebar.caption(
                "\u2139\ufe0f This protein did NOT pass both EDA filters — "
                "still fine to explore, just not a validated candidate biomarker."
            )

st.sidebar.markdown("### What do you want to see?")
view_mode = st.sidebar.radio(
    "View",
    ["Across 8 groups", "Genotype comparison", "Treatment response"],
    format_func=lambda v: {
        "Across 8 groups": "Across 8 groups \u2014 compare all experimental groups at once",
        "Genotype comparison": "Genotype comparison \u2014 Control vs Down-syndrome model",
        "Treatment response": "Treatment response \u2014 did the drug help?",
    }[v]
)

st.sidebar.markdown("---")
st.sidebar.caption(
    "Data: UCI Mice Protein Expression dataset (Higuera et al., PLoS ONE 2015)"
)

# ---------------------------------------------------------------
# Main panel
# ---------------------------------------------------------------
st.title("\U0001F9E0 The Down Syndrome Learning Rescue Mission")
st.caption(
    "Interactively explore how each protein's expression level varies across "
    "genotype, treatment, and behavior groups."
)

col1, col2, col3 = st.columns(3)
col1.metric("Total mice", len(df))
col2.metric("Proteins available", len(protein_cols))
col3.metric("Groups", df["class"].nunique())

def render_protein_explorer():
    st.caption(
        "Use the sidebar to pick a protein and a view. If you're not sure where to "
        "start, use the **Candidate biomarkers** quick-select instead of the full "
        "alphabetical list — those are the proteins that passed statistical testing."
    )
    st.markdown(f"## `{selected_protein}`")

    if view_mode == "Across 8 groups":
        st.markdown(
            "**Violin + box + individual mice**, grouped and colored by Genotype so the "
            "Control-vs-Trisomic split is visible at a glance, instead of 8 unordered bars. "
            "The violin shape shows the full distribution (not just mean/std), and each dot is one mouse."
        )
        with st.expander("\U0001F4D6 Decode the group labels (e.g. `t-CS-m`)"):
            st.markdown(
                "- **1st letter** — `c` = Control, `t` = Trisomic (Ts65Dn)\n"
                "- **Middle** — `CS` = real learning test (context-then-shock), "
                "`SC` = control condition (shock-then-context, no chance to learn)\n"
                "- **Last letter** — `s` = Saline (placebo), `m` = Memantine (drug)"
            )

        # Order groups logically: Control groups first, then Trisomic, each split by Treatment/Behavior
        group_order = sorted(df["class"].unique(), key=lambda c: (c[0] != "c", c))
        genotype_map = {"c": "Control", "t": "Ts65Dn"}
        plot_df = df[["class", selected_protein]].copy()
        plot_df["Genotype"] = plot_df["class"].str[0].map(genotype_map)

        fig, ax = plt.subplots(figsize=(11, 6))
        sns.violinplot(
            x="class", y=selected_protein, hue="Genotype", data=plot_df, ax=ax,
            order=group_order, palette={"Control": "#5DCAA5", "Ts65Dn": "#D85A30"},
            inner="quartile", cut=0, dodge=False
        )
        sns.stripplot(
            x="class", y=selected_protein, data=plot_df, ax=ax,
            order=group_order, color="black", size=2.5, alpha=0.35, jitter=0.2
        )
        ax.set_title(f"{selected_protein} across all 8 groups (grouped by Genotype)")
        ax.set_xlabel("Group (Control groups on left, Trisomic on right)")
        plt.xticks(rotation=30)
        ax.legend(title="Genotype", loc="upper right")
        plt.tight_layout()
        st.pyplot(fig)

        group_means = df.groupby("class")[selected_protein].agg(["mean", "std"]).reindex(group_order)

        behavior_map = {"CS": "Real learning test", "SC": "Control condition"}
        treatment_map = {"s": "Saline", "m": "Memantine"}
        display_table = group_means.reset_index().rename(columns={"class": "Group", "mean": "Mean", "std": "Std Dev"})
        display_table["Genotype"] = display_table["Group"].str[0].map(genotype_map)
        display_table["Behavior"] = display_table["Group"].str.split("-").str[1].map(behavior_map)
        display_table["Treatment"] = display_table["Group"].str.split("-").str[2].map(treatment_map)
        display_table = display_table[["Group", "Genotype", "Behavior", "Treatment", "Mean", "Std Dev"]]
        st.dataframe(display_table, use_container_width=True, hide_index=True)

        stats_dict = {idx: {"mean": row["mean"], "std": row["std"]} for idx, row in group_means.iterrows()}
        highest = max(stats_dict.items(), key=lambda kv: kv[1]["mean"])
        lowest = min(stats_dict.items(), key=lambda kv: kv[1]["mean"])
        most_variable = max(stats_dict.items(), key=lambda kv: kv[1]["std"])

        st.markdown("#### \U0001F4CA What the data shows")
        scol1, scol2, scol3 = st.columns(3)
        scol1.metric("Highest mean", highest[0], f"{highest[1]['mean']:.3f}")
        scol2.metric("Lowest mean", lowest[0], f"{lowest[1]['mean']:.3f}")
        scol3.metric("Largest spread (std dev)", most_variable[0], f"{most_variable[1]['std']:.3f}")

        st.markdown("#### \U0001F9EC Why this protein matters")
        render_biology_profile(selected_protein)

        dcol1, dcol2 = st.columns(2)
        dcol1.download_button(
            "\U0001F4E5 Download chart as PNG",
            data=fig_to_png_bytes(fig),
            file_name=f"{selected_protein}_across_groups.png",
            mime="image/png",
        )
        dcol2.download_button(
            "\U0001F4E5 Download data as CSV",
            data=df_to_csv_bytes(display_table),
            file_name=f"{selected_protein}_across_groups.csv",
            mime="text/csv",
        )

    elif view_mode == "Genotype comparison":
        st.markdown(
            "**Raincloud plot** \u2014 half-violin (distribution shape) + boxplot (median/quartiles) "
            "+ jittered points (individual mice) \u2014 comparing **Control** vs **Ts65Dn (trisomic)** mice."
        )
        plot_data = df[["Genotype", selected_protein]].copy()

        fig, ax = plt.subplots(figsize=(8, 6))
        sns.violinplot(
            x="Genotype", y=selected_protein, hue="Genotype", data=plot_data, ax=ax,
            palette={"Control": "#5DCAA5", "Ts65Dn": "#D85A30"},
            inner=None, cut=0, legend=False, width=0.6
        )
        # Narrow the violins to one side visually by overlaying a boxplot + strip on top
        sns.boxplot(
            x="Genotype", y=selected_protein, data=plot_data, ax=ax,
            width=0.15, showcaps=True, boxprops={"facecolor": "white", "alpha": 0.8},
            whiskerprops={"linewidth": 1.5}, medianprops={"color": "black", "linewidth": 2}
        )
        sns.stripplot(
            x="Genotype", y=selected_protein, data=plot_data, ax=ax,
            color="black", size=3, alpha=0.3, jitter=0.15
        )
        ax.set_title(f"{selected_protein}: Control vs Trisomic")
        plt.tight_layout()
        st.pyplot(fig)

        ctrl_mean = df[df.Genotype == "Control"][selected_protein].mean()
        tris_mean = df[df.Genotype == "Ts65Dn"][selected_protein].mean()
        pct_diff = (tris_mean - ctrl_mean) / ctrl_mean * 100
        c1, c2, c3 = st.columns(3)
        c1.metric("Control mean", f"{ctrl_mean:.3f}")
        c2.metric("Trisomic mean", f"{tris_mean:.3f}")
        c3.metric("% difference", f"{pct_diff:+.1f}%")

        genotype_table = df[["Genotype", selected_protein]].groupby("Genotype")[selected_protein] \
            .agg(["mean", "std", "count"]).rename(columns={"mean": "Mean", "std": "Std Dev", "count": "N"})
        st.markdown("#### \U0001F4CA What the data shows")
        st.dataframe(genotype_table, use_container_width=True)

        st.markdown("#### \U0001F9EC Why this protein matters")
        render_biology_profile(selected_protein)

        dcol1, dcol2 = st.columns(2)
        dcol1.download_button(
            "\U0001F4E5 Download chart as PNG",
            data=fig_to_png_bytes(fig),
            file_name=f"{selected_protein}_genotype_comparison.png",
            mime="image/png",
        )
        dcol2.download_button(
            "\U0001F4E5 Download data as CSV",
            data=df_to_csv_bytes(genotype_table),
            file_name=f"{selected_protein}_genotype_comparison.csv",
            mime="text/csv",
        )

    else:  # Treatment response
        st.markdown(
            "**Raincloud plot + mean-shift line** \u2014 shows the full distribution for "
            "**Control**, **Trisomic + Memantine**, and **Trisomic + Saline**, with a dashed "
            "line connecting the three group means so the direction and size of any shift "
            "toward control is immediately visible \u2014 not just implied by comparing numbers."
        )
        control = df[df.Genotype == "Control"][selected_protein]
        treated = df[(df.Genotype == "Ts65Dn") & (df.Treatment == "Memantine")][selected_protein]
        untreated = df[(df.Genotype == "Ts65Dn") & (df.Treatment == "Saline")][selected_protein]

        group_order_names = ["Trisomic + Saline", "Trisomic + Memantine", "Control"]
        plot_df = pd.concat([
            pd.DataFrame({"Group": "Trisomic + Saline", selected_protein: untreated.values}),
            pd.DataFrame({"Group": "Trisomic + Memantine", selected_protein: treated.values}),
            pd.DataFrame({"Group": "Control", selected_protein: control.values}),
        ], ignore_index=True)

        fig, ax = plt.subplots(figsize=(9, 6))
        sns.violinplot(
            x="Group", y=selected_protein, hue="Group", data=plot_df, ax=ax,
            order=group_order_names, palette=["#D85A30", "#1D9E75", "#5DCAA5"],
            inner=None, cut=0, legend=False, width=0.6
        )
        sns.boxplot(
            x="Group", y=selected_protein, data=plot_df, ax=ax, order=group_order_names,
            width=0.15, boxprops={"facecolor": "white", "alpha": 0.8},
            whiskerprops={"linewidth": 1.5}, medianprops={"color": "black", "linewidth": 2}
        )
        sns.stripplot(
            x="Group", y=selected_protein, data=plot_df, ax=ax, order=group_order_names,
            color="black", size=3, alpha=0.25, jitter=0.15
        )
        # Mean-shift line: untreated -> treated -> control
        means = [untreated.mean(), treated.mean(), control.mean()]
        ax.plot(range(3), means, color="#0C447C", marker="D", markersize=9,
                linewidth=2.5, linestyle="--", zorder=10, label="Group mean")
        ax.legend(loc="upper left")
        ax.set_title(f"{selected_protein}: does treatment shift the mean toward control?")
        ax.set_xlabel("")
        plt.tight_layout()
        st.pyplot(fig)

        treatment_table = pd.DataFrame({
            "Group": ["Control", "Trisomic + Memantine", "Trisomic + Saline"],
            "Mean": [control.mean(), treated.mean(), untreated.mean()],
            "Std Dev": [control.std(), treated.std(), untreated.std()],
            "N": [len(control), len(treated), len(untreated)],
        }).set_index("Group")

        st.markdown("#### \U0001F4CA What the data shows")
        mcol1, mcol2, mcol3 = st.columns(3)
        mcol1.metric("Control mean", f"{control.mean():.3f}")
        mcol2.metric("Trisomic + Memantine mean", f"{treated.mean():.3f}",
                     f"{treated.mean() - untreated.mean():+.3f} vs untreated")
        mcol3.metric("Trisomic + Saline mean", f"{untreated.mean():.3f}")
        st.dataframe(treatment_table, use_container_width=True)

        st.markdown("#### \U0001F9EC Why this protein matters")
        render_biology_profile(selected_protein)

        dcol1, dcol2 = st.columns(2)
        dcol1.download_button(
            "\U0001F4E5 Download chart as PNG",
            data=fig_to_png_bytes(fig),
            file_name=f"{selected_protein}_treatment_response.png",
            mime="image/png",
        )
        dcol2.download_button(
            "\U0001F4E5 Download data as CSV",
            data=df_to_csv_bytes(treatment_table),
            file_name=f"{selected_protein}_treatment_response.csv",
            mime="text/csv",
        )

        dist_treated = abs(treated.mean() - control.mean())
        dist_untreated = abs(untreated.mean() - control.mean())
        shifted = dist_treated < dist_untreated

        if shifted:
            st.success(
                f"Treatment moved {selected_protein} closer to the control level "
                f"(distance dropped from {dist_untreated:.3f} to {dist_treated:.3f})."
            )
        else:
            st.warning(
                f"Treatment did NOT move {selected_protein} closer to control for this protein "
                f"(distance went from {dist_untreated:.3f} to {dist_treated:.3f})."
            )

        if candidates is not None:
            row = candidates[candidates["protein"] == selected_protein]
            if len(row):
                row = row.iloc[0]
                is_candidate = bool(row.get("shifted_toward_control", False)) and \
                    bool(row.get("significant", False))
                p_val = row.get("p_value", None)
                if p_val is not None:
                    verdict = "statistically significant" if p_val < 0.05 else "not statistically significant"
                    plain_english = (
                        "This means the difference between treated and untreated mice is "
                        "unlikely to be random chance."
                        if p_val < 0.05 else
                        "This means we can't rule out that the difference is just random "
                        "variation between mice, not a real drug effect."
                    )
                    st.info(
                        f"**Welch's t-test p-value: {p_val:.4f}** ({verdict} at the "
                        f"standard p < 0.05 threshold). {plain_english}\n\n"
                        f"{'\u2705 **This protein IS one of the validated candidate biomarkers** from the EDA — it both shifted toward control AND passed this test.' if is_candidate else '\u26a0\ufe0f This protein did not pass both EDA filters (shift + significance), so it is not on the validated candidate list.'}"
                    )





@st.cache_data
def compute_family_correlations(_df, _protein_cols, _families):
    """Returns (corr_matrix, baseline_mean_abs_r, per_family summary dict).

    baseline_mean_abs_r is the average |correlation| across ALL pairs of the
    77 proteins -- the bar a family needs to clear before we call its
    coherence 'real' rather than just the general background co-variation
    that exists across the whole protein panel.
    """
    corr = _df[_protein_cols].corr()
    all_vals = corr.values
    iu = np.triu_indices_from(all_vals, k=1)
    baseline = float(np.abs(all_vals[iu]).mean())

    summary = {}
    for fam, prots in _families.items():
        prots = [p for p in prots if p in _protein_cols]
        if len(prots) < 2:
            summary[fam] = {"proteins": prots, "mean_abs_r": None, "min_abs_r": None, "max_abs_r": None}
            continue
        sub = corr.loc[prots, prots].values
        iu2 = np.triu_indices_from(sub, k=1)
        summary[fam] = {
            "proteins": prots,
            "mean_abs_r": float(np.abs(sub[iu2]).mean()),
            "min_abs_r": float(np.abs(sub[iu2]).min()),
            "max_abs_r": float(np.abs(sub[iu2]).max()),
        }
    return corr, baseline, summary


def render_pathway_groups():
    st.subheader("\U0001F9EA Biological Pathway Grouping (sanity check)")
    st.markdown(
        "The 77 proteins in this panel belong to known biological families \u2014 "
        "receptor subunits that physically assemble together, enzyme families, "
        "signaling cascades. Grouping candidate proteins this way is a "
        "**sanity check**, not new evidence on its own: if a family's members "
        "move together in this dataset, that's a small extra reason to trust the "
        "signal is biology rather than statistical noise. If they don't move "
        "together, that doesn't invalidate anything \u2014 it just means "
        "correlation-of-expression-level isn't the right lens for that kind of group "
        "(more on that below)."
    )

    corr, baseline, summary = compute_family_correlations(df, protein_cols, PROTEIN_FAMILIES)

    st.info(
        f"\U0001F4CA **Baseline:** across all {len(protein_cols)} proteins, the average "
        f"pairwise correlation is already **|r| = {baseline:.3f}** \u2014 this dataset has "
        f"general background co-variation everywhere. A family only tells you something "
        f"extra if it clears this baseline by a clear margin."
    )

    family_name = st.selectbox("Choose a biological family to inspect", list(PROTEIN_FAMILIES.keys()))
    fam_info = summary[family_name]
    prots = fam_info["proteins"]

    if fam_info["mean_abs_r"] is None:
        st.warning("Fewer than 2 of this family's proteins are in the dataset.")
        return

    mean_r = fam_info["mean_abs_r"]
    margin = mean_r - baseline

    # Honest, pre-set verdict logic: a clear margin above baseline = coherent;
    # close to or below baseline = not coherent as a block, even if one pair is strong.
    if margin > 0.15:
        verdict_icon = "\u2705"
        verdict = (
            f"**Coherent as a group** \u2014 mean |r| = {mean_r:.3f}, "
            f"{margin:+.3f} above the {baseline:.3f} baseline. These proteins genuinely "
            f"move together in this dataset, consistent with them being physically or "
            f"functionally tied together."
        )
    elif margin > 0.05:
        verdict_icon = "\U0001F7E1"
        verdict = (
            f"**Modestly coherent** \u2014 mean |r| = {mean_r:.3f}, only "
            f"{margin:+.3f} above the {baseline:.3f} baseline. Some real signal, but not "
            f"strong enough to lean on by itself."
        )
    else:
        verdict_icon = "\u26A0\uFE0F"
        verdict = (
            f"**Not coherent as a block** \u2014 mean |r| = {mean_r:.3f}, essentially at "
            f"(or below) the {baseline:.3f} dataset-wide baseline. Any strong individual pair "
            f"below is doing the work, not the family as a whole \u2014 see the heatmap and "
            f"pair list. This is expected for signaling cascades: a cascade is about "
            f"*activation state* moment-to-moment, not steady resting expression level "
            f"across different mice, and negative feedback loops can even push some pairs "
            f"negative."
        )

    st.markdown(f"### {verdict_icon} {family_name}")
    st.markdown(verdict)

    # Heatmap of this family's members
    sub_corr = corr.loc[prots, prots]
    fig, ax = plt.subplots(figsize=(1.1 * len(prots) + 2, 1.1 * len(prots) + 1))
    sns.heatmap(
        sub_corr, ax=ax, annot=True, fmt=".2f", cmap="RdBu_r", vmin=-1, vmax=1,
        square=True, cbar_kws={"label": "correlation (r)"}
    )
    ax.set_title(f"{family_name}: pairwise correlation")
    plt.tight_layout()
    st.pyplot(fig)

    st.caption(
        "This correlation check is this project's own analysis of the dataset "
        "(KNN-imputed expression levels, Pearson correlation) \u2014 the source paper "
        "(Higuera et al. 2015) does not report family-level correlation coherence; "
        "it ranks individual proteins using self-organizing maps."
    )

    with st.expander("\U0001F9EC What each protein in this family does"):
        for p in prots:
            info = BIOLOGY_PROFILES.get(p)
            if info:
                st.markdown(f"**`{p}`** \u2014 {info['role']}")


tab1, tab2 = st.tabs([
    "\U0001F4D6 Story & Background",
    "\U0001F4CA Protein Explorer",
])

with tab1:
    st.markdown(
        """
This tool explores a real experiment on mice studying **Down syndrome** and a
possible drug treatment.

**The core question:** did Memantine shift trisomic mice's protein levels
*closer to* healthy Control-mouse levels? If so, which specific proteins
respond the most — those are candidate **biomarkers** worth studying further.

To understand every chart in this app, you just need to know the 3 variables
that were changed in this experiment:
        """
    )

    gcol1, gcol2, gcol3 = st.columns(3)
    with gcol1:
        st.markdown("#### \U0001F9EC Genotype — *who are they?*")
        st.markdown(
            "- **Control**: normal, healthy mice\n"
            "- **Ts65Dn**: mice bred to model Down syndrome (an extra copy of certain genes)"
        )
    with gcol2:
        st.markdown("#### \U0001F48A Treatment — *what did they get?*")
        st.markdown(
            "- **Saline**: a placebo (no drug)\n"
            "- **Memantine**: the experimental drug being tested"
        )
    with gcol3:
        st.markdown("#### \U0001F52C Behavior — *what test did they do?*")
        st.markdown(
            "- **C/S**: explored the cage, **then** got a mild shock — this gives a real "
            "chance to learn \"this place = danger\"\n"
            "- **S/C**: got the shock **immediately**, before exploring — no chance to "
            "learn that connection (a control condition, not a \"failed\" mouse)"
        )

    st.markdown(
        """
**Important:** the C/S vs S/C label by itself does NOT mean "learned" vs
"failed." Whether a mouse actually learned is worked out by comparing
**Genotype + Treatment within the C/S group** — that's exactly what the
**"Treatment response"** view (in the Protein Explorer tab) does: Control
(learned normally) vs Trisomic+Saline (failed to learn) vs Trisomic+Memantine
(did the drug help it learn?).

**Reading a group label, left to right** — e.g. `t-CS-m`:
| Part | Meaning |
|---|---|
| `t` | Trisomic mouse (Ts65Dn) |
| `CS` | Took the real learning test (context-then-shock) |
| `m` | Given Memantine |

So `t-CS-m` = "a Down-syndrome-model mouse, given the real learning test, treated with the drug."
        """
    )

    st.markdown("---")
    st.subheader("\U0001F4CD All 77 proteins reduced to a 2D map (PCA)")
    st.markdown(
        "Each mouse has 77 protein measurements — far too many to plot directly "
        "(a chart only has 2 or 3 axes, not 77). "
        "**PCA** (Principal Component Analysis) finds the 2 directions that capture "
        "the most variation across all 77 proteins, so we can plot every mouse as a "
        "single point and see whether groups form visually distinct clusters."
    )

    @st.cache_data
    def compute_pca(_df, _protein_cols):
        from sklearn.preprocessing import StandardScaler
        X_scaled = StandardScaler().fit_transform(_df[_protein_cols])
        pca = PCA(n_components=2)
        result = pca.fit_transform(X_scaled)
        return result, pca.explained_variance_ratio_

    pca_result, explained_var = compute_pca(df, protein_cols)
    pca_df = pd.DataFrame(pca_result, columns=["Dimension 1", "Dimension 2"])
    pca_df["Mouse Group"] = df["class"].values
    pca_df["Genotype"] = df["Genotype"].values

    st.info(
        "\U0001F4A1 **How to read the chart below:** each dot is one mouse. Hover over "
        "a dot to see its group. If Control and Trisomic groups form visually separate "
        "regions (rather than one mixed-together blob), that means Genotype is a real "
        "driver of overall protein patterns. This is a **general, reduced-dimension view** "
        "across all 77 proteins at once — it's a different question from \"did treatment "
        "shift any *specific* protein toward control,\" which is what the statistical "
        "tests in the Protein Explorer tab answer directly. Together they give both the "
        "big-picture pattern and the specific evidence."
    )

    fig_pca = px.scatter(
        pca_df, x="Dimension 1", y="Dimension 2",
        color="Mouse Group", symbol="Genotype",
        title=f"2D protein map (PC1: {explained_var[0]*100:.1f}% variance, PC2: {explained_var[1]*100:.1f}% variance)",
        template="plotly_dark",
        hover_data=["Mouse Group"],
    )
    fig_pca.update_traces(marker=dict(size=7, opacity=0.7))
    st.plotly_chart(fig_pca, use_container_width=True)

with tab2:
    render_protein_explorer()
    st.markdown("---")
    render_pathway_groups()


st.markdown("---")
if candidates is not None:
    with st.expander("\U0001F4E5 Download full statistical results (all 77 proteins)"):
        st.dataframe(candidates)
        st.download_button(
            "Download full treatment_response_analysis.csv",
            data=df_to_csv_bytes(candidates.set_index("protein")),
            file_name="treatment_response_analysis_full.csv",
            mime="text/csv",
        )

st.caption(
    "Built for the IDEAS TIH Summer Internship project: "
    "Down Syndrome Drug-Response Biomarker Analysis."
)
